FROM node:22 AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_DECAPBRIDGE_API_URL
ARG VITE_DECAPBRIDGE_GATEWAY_URL
ARG VITE_DECAPBRIDGE_IS_SELFHOSTED
ARG VITE_DECAPBRIDGE_SITE_URL
ARG VITE_DECAPBRIDGE_SITE_NAME
ARG VITE_DECAPBRIDGE_SITE_LOGO
ARG VITE_DECAPBRIDGE_THEME_COLOR
ARG VITE_DECAPBRIDGE_THEME_RADIUS

ENV VITE_DECAPBRIDGE_API_URL=$VITE_DECAPBRIDGE_API_URL
ENV VITE_DECAPBRIDGE_GATEWAY_URL=$VITE_DECAPBRIDGE_GATEWAY_URL
ENV VITE_DECAPBRIDGE_IS_SELFHOSTED=$VITE_DECAPBRIDGE_IS_SELFHOSTED
ENV VITE_DECAPBRIDGE_SITE_URL=$VITE_DECAPBRIDGE_SITE_URL
ENV VITE_DECAPBRIDGE_SITE_NAME=$VITE_DECAPBRIDGE_SITE_NAME
ENV VITE_DECAPBRIDGE_SITE_LOGO=$VITE_DECAPBRIDGE_SITE_LOGO
ENV VITE_DECAPBRIDGE_THEME_COLOR=$VITE_DECAPBRIDGE_THEME_COLOR
ENV VITE_DECAPBRIDGE_THEME_RADIUS=$VITE_DECAPBRIDGE_THEME_RADIUS

RUN npm run build

FROM node:22-slim

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000

CMD ["npx", "vite", "preview", "--host", "0.0.0.0", "--port", "3000"]
