# =======================================
# DecapCMS configuration
# Learn more at https://decapcms.org/
# =======================================

# backend:
#   name: git-gateway
#   repo: loteoo/decap-bridge-web
#   branch: main
#   identity_url: http://localhost:8055/sites/e7ca3efb-dca4-443d-a4b1-236ceab96dd6
#   gateway_url: http://localhost:8081

local_backend: true
backend:
  name: git-gateway

site_url: https://decapbridge.com
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

locale: en

slug:
  encoding: ascii
  clean_accents: true

media_folder: public/uploads
public_folder: /uploads

# ====================================
# Utilities (reusable yaml anchors)
# ====================================

meta_title: &meta-title
  label: "Title"
  name: "title"
  widget: "string"
  hint: "Aim for 50 to 60 characters."

meta_description: &meta-description
  label: "Description"
  name: "description"
  hint: "Aim for 120 to 158 characters."
  widget: "text"

meta_block: &meta-block
  label: "Meta"
  name: "meta"
  widget: "object"
  hint: "Search engines, social media sharing & bots."
  fields:
    - *meta-title
    - *meta-description

body_field: &body-field
  label: "Body"
  name: "body"
  widget: "markdown"

email_input: &email-input
  label: "Email input"
  name: "email"
  widget: "object"
  fields:
    - { label: "Label", name: "label", widget: "string" }
    - { label: "Placeholder", name: "placeholder", widget: "string" }

password_input: &password-input
  label: "Password input"
  name: "password"
  widget: "object"
  fields:
    - { label: "Label", name: "label", widget: "string" }
    - { label: "Placeholder", name: "placeholder", widget: "string" }

first_name_input: &first-name-input
  label: "First name input"
  name: "first_name"
  widget: "object"
  fields:
    - { label: "Label", name: "label", widget: "string" }
    - { label: "Placeholder", name: "placeholder", widget: "string" }

last_name_input: &last-name-input
  label: "Last name input"
  name: "last_name"
  widget: "object"
  fields:
    - { label: "Label", name: "label", widget: "string" }
    - { label: "Placeholder", name: "placeholder", widget: "string" }

collections:
  # ============================
  # Global site settings
  # ============================
  - label: Settings
    name: settings
    editor:
      preview: false
    files:
      # Site settings
      # ==============================
      - name: meta
        label: Site settings
        file: content/settings/site.json
        fields:
          - { label: "Site URL", name: "site_url", widget: "string" }
          - { label: "Site name", name: "site_name", widget: "string" }
          - { label: "Site title", name: "site_title", widget: "string" }
          - {
              label: "Site description",
              name: "site_description",
              widget: "text",
            }

      # Misc UI elements
      # ==============================
      - name: misc
        label: Misc UI elements
        file: content/settings/misc.json
        fields:
          - { label: "Search label", name: "search_label", widget: "string" }
          - { label: "Empty label", name: "empty_label", widget: "string" }
          - {
              label: "Footer pages column",
              name: "footer_pages_column",
              widget: "string",
            }
          - {
              label: "Footer text pages column",
              name: "footer_text_pages_column",
              widget: "string",
            }
          - label: "Social Links"
            name: "social_links"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - { label: "Url", name: "url", widget: "string" }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Icon", name: "icon", widget: "string" }
          - { label: "Log out", name: "logout", widget: "string" }
          - {
              label: "Logged out message",
              name: "logged_out_success",
              widget: "string",
            }
          - { label: "Token expired", name: "token_expired", widget: "string" }
          - {
              label: "Token expired message",
              name: "token_expired_message",
              widget: "string",
            }

  # ============================
  # Main pages
  # ============================
  - label: Main Pages
    name: pages
    editor:
      preview: false
    files:
      # Home page
      # ===================
      - name: index
        label: Home
        file: content/pages/index.json
        fields:
          - *meta-block
          - {
              label: "Hero title",
              name: "hero_title",
              widget: "markdown",
              minimal: true,
            }

      # Contact page
      # ===================
      - name: contact
        label: Contact
        file: content/pages/contact.json
        fields:
          - *meta-block
          - { label: "Name label", name: "name_label", widget: "string" }
          - { label: "Email label", name: "email_label", widget: "string" }
          - { label: "Message label", name: "message_label", widget: "string" }
          - { label: "Submit button", name: "submit_button", widget: "string" }
          - {
              label: "Success message",
              name: "success_message",
              widget: "string",
            }
          - { label: "Error message", name: "error_message", widget: "string" }

  # ============================
  # Auth pages
  # ============================
  - label: Auth Pages
    name: auth
    editor:
      preview: false
    i18n:
      structure: single_file
    files:
      # Log in page
      # ===================
      - name: auth/login
        label: Log in
        file: content/pages/auth/login.json
        fields:
          - *meta-block
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Sub-header", name: "sub_header", widget: "string" }
          - {
              label: "Create account",
              name: "create_account",
              widget: "string",
            }
          - *email-input
          - *password-input
          - {
              label: "Forgot password",
              name: "forgot_password",
              widget: "string",
            }
          - { label: "Login button", name: "login_button", widget: "string" }

      # Sign up page
      # ===================
      - name: auth/signup
        label: Sign up
        file: content/pages/auth/signup.json
        fields:
          - *meta-block
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Sub-header", name: "sub_header", widget: "string" }
          - { label: "Login", name: "login", widget: "string" }
          - *first-name-input
          - *last-name-input
          - *email-input
          - *password-input
          - { label: "Submit button", name: "submit_button", widget: "string" }

      # Forgot password page
      # ===================
      - name: auth/password/forgot
        label: Forgot password
        file: content/pages/auth/password/forgot.json
        fields:
          - *meta-block
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Sub-header", name: "sub_header", widget: "string" }
          - *email-input
          - { label: "Login link", name: "login_link", widget: "string" }
          - { label: "Submit button", name: "submit_button", widget: "string" }
          - { label: "Success title", name: "success_title", widget: "string" }
          - {
              label: "Success description",
              name: "success_description",
              widget: "string",
            }
          - { label: "Home link", name: "home_link", widget: "string" }

      # Reset password page
      # ===================
      - name: auth/password/reset
        label: Reset password
        file: content/pages/auth/password/reset.json
        fields:
          - *meta-block
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Sub-header", name: "sub_header", widget: "string" }
          - *password-input
          - { label: "Submit button", name: "submit_button", widget: "string" }
          - {
              label: "Success message",
              name: "success_message",
              widget: "string",
            }
          - {
              label: "Token missing error",
              name: "token_missing",
              widget: "string",
            }
          - {
              label: "Request password",
              name: "request_password",
              widget: "string",
            }

  # ============================
  # Dashboard pages
  # ============================
  - label: Dashboard Pages
    name: dashboard
    editor:
      preview: false
    i18n:
      structure: single_file
    files:
      # Profile page
      # ===================
      - name: dashboard/profile
        label: Profile
        file: content/pages/dashboard/profile.json
        fields:
          - *meta-block
          - *first-name-input
          - *last-name-input
          - { label: "Save", name: "save", widget: "string" }

      # Activity page
      # ===================
      - name: dashboard/activity
        label: Activity
        file: content/pages/dashboard/activity.json
        fields:
          - *meta-block

      # Settings page
      # ===================
      - name: dashboard/settings
        label: Settings
        file: content/pages/dashboard/settings.json
        fields:
          - *meta-block
          - {
              label: "Color scheme heading",
              name: "color_scheme_heading",
              widget: "string",
            }
          - {
              label: "Dark mode toggle",
              name: "dark_mode_toggle",
              widget: "string",
            }
          - {
              label: "Reset password heading",
              name: "reset_password_heading",
              widget: "string",
            }
          - {
              label: "Reset password sub heading",
              name: "reset_password_sub_heading",
              widget: "string",
            }
          - {
              label: "Reset password button",
              name: "reset_password_button",
              widget: "string",
            }
          - {
              label: "Reset password success title",
              name: "reset_password_success_title",
              widget: "string",
            }
          - {
              label: "Reset password success message",
              name: "reset_password_success_message",
              widget: "string",
            }
          - {
              label: "Delete account heading",
              name: "delete_account_heading",
              widget: "string",
            }
          - {
              label: "Delete account sub heading",
              name: "delete_account_sub_heading",
              widget: "string",
            }
          - {
              label: "Delete account button",
              name: "delete_account_button",
              widget: "string",
            }
          - {
              label: "Confirm account deletion heading",
              name: "confirm_account_deletion_heading",
              widget: "string",
            }
          - {
              label: "Confirm account deletion instruction",
              name: "confirm_account_deletion_instruction",
              widget: "string",
            }
          - {
              label: "Confirm account deletion warning",
              name: "confirm_account_deletion_warning",
              widget: "string",
            }
          - {
              label: "Confirm account deletion button",
              name: "confirm_account_deletion_button",
              widget: "string",
            }
          - {
              label: "Account deletion success title",
              name: "delete_account_success_title",
              widget: "string",
            }
          - {
              label: "Account deletion success message",
              name: "delete_account_success_message",
              widget: "string",
            }

  # ============================
  # Content collections
  # ============================

  # Text Pages
  # ============================
  - label: Text Pages
    name: text-pages
    folder: content/collections/text-pages
    create: true
    slug: "{{key}}"
    identifier_field: "meta.title"
    fields:
      - *meta-block
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options: ["legal"]
      - *body-field
